services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: paymentflowcloud-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  rabbitmq:
    image: rabbitmq:management
    container_name: paymentflowcloud-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 12

  seq:
    image: datalust/seq
    container_name: paymentflowcloud-seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:80"

  api:
    build:
      context: .
      dockerfile: PaymentFlowCloud.Api/Dockerfile
    container_name: paymentflowcloud-api
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__SqlServer: "Server=sqlserver,1433;Database=PaymentFlowCloudDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
      RabbitMQ__QueueName: "payment-created"
      Seq__ServerUrl: "http://seq:80"
    ports:
      - "5147:8080"

  worker:
    build:
      context: .
      dockerfile: PaymentFlowCloud.Worker/Dockerfile
    container_name: paymentflowcloud-worker
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      api:
        condition: service_started
    environment:
      DOTNET_ENVIRONMENT: "Development"
      ConnectionStrings__SqlServer: "Server=sqlserver,1433;Database=PaymentFlowCloudDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
      RabbitMQ__QueueName: "payment-created"
      Seq__ServerUrl: "http://seq:80"

  web:
    build:
      context: .
      dockerfile: PaymentFlowCloud.Web/Dockerfile
    container_name: paymentflowcloud-web
    depends_on:
      api:
        condition: service_started
    ports:
      - "5173:80"

  k6:
    image: grafana/k6
    profiles:
      - loadtest
    depends_on:
      api:
        condition: service_started
    environment:
      BASE_URL: "http://api:8080"
      VUS: "20"
      ITERATIONS: "20"
    volumes:
      - ./scripts:/scripts:ro
    command: ["run", "/scripts/payment-idempotency.k6.js"]
